# https://github.com/troessner/reek/blob/master/docs/Code-Smells.md
---
detectors:
  FeatureEnvy:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  TooManyStatements:
    enabled: false
  LongParameterList:
    enabled: false
  NilCheck:
    enabled: false
  ControlParameter:
    enabled: false
  BooleanParameter:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  UtilityFunction:
    enabled: false
